name: Deploy to Portainer

on:
  push:
    branches:
      - '*'
    paths:
      - 'React/'
  pull_request:
    branches:
      - '*'
    paths:
      - 'React/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - 
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: React/
          file: Dockerfile
          tags: ${{ secrets.DOCKER_REGISTRY }}/emontazysta/frontend:latest
          push: true
      - 
        name: Create stack in Portainer
        uses: carlrygart/portainer-stack-deploy@v1.3.0
        with:
          stack-definition: .build/stack-file.yml
          portainer-host: ${{ secrets.PORTAINER_URL }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: frontend
          endpoint-id: 1
